In [1]:
import pandas as pd
from GNN.architecture import GNNTrainer
import torch
import pickle
from sklearn.metrics import ndcg_score
import numpy as np
import random
from numpy import unravel_index

## LOAD THE DATASET

In [2]:
train_data = pd.read_csv("data/movielens/train.csv", index_col=0)
val_data = pd.read_csv("data/movielens/test.csv", index_col=0)
movie_features = pd.read_csv("data/movielens/movie_features.csv", index_col=0)
train_pair_data = np.loadtxt("data/movielens/train_pair.csv", dtype=np.int64, delimiter=",")
val_pair_data = np.loadtxt("data/movielens/val_pair.csv", dtype=np.int64, delimiter=",")

/tmp/ipykernel_2043270/1152477808.py:4: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  train_pair_data = np.loadtxt("data/movielens/train_pair.csv", dtype=np.int64, delimiter=",")
/tmp/ipykernel_2043270/1152477808.py:5: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  val_pair_data = np.loadtxt("data/movielens/val_pair.csv", dtype=np.int64, delimiter=",")

## NEGATIVE SAMPLING - FOR 1 POSITVE SAMPLE THERE WILL BE 100 NEGATIVE SAMPLES

In [3]:
all_users = set(train_data['userId'].unique())
all_items = set(train_data['productId'].unique())

In [4]:
users_negative_samples = {}
for i,u in enumerate(all_users):
    user_u_positive_items = set(train_data[train_data['userId']==u]['productId'].unique())
    user_u_negative_items = all_items.difference(user_u_positive_items)
    users_negative_samples[u] = user_u_negative_items

In [5]:
all_pairs = []
for i ,(userId, productId_pos, _, _) in enumerate(train_data.values):
    sample_negative_items = random.sample(list(users_negative_samples[userId]), 100)
    pair_data_u = [[userId, productId_pos, userId, productId_neg] for productId_neg in sample_negative_items]
    all_pairs.extend(pair_data_u)
    if (i+1) % 1000 == 0:
        print(f"{i+1} records complete")

1000 records complete
2000 records complete
3000 records complete
4000 records complete
5000 records complete
6000 records complete
7000 records complete
8000 records complete
9000 records complete
10000 records complete
11000 records complete
12000 records complete
13000 records complete
14000 records complete
15000 records complete
16000 records complete
17000 records complete
18000 records complete
19000 records complete
20000 records complete
21000 records complete
22000 records complete
23000 records complete
24000 records complete
25000 records complete
26000 records complete
27000 records complete
28000 records complete
29000 records complete
30000 records complete
31000 records complete
32000 records complete
33000 records complete
34000 records complete
35000 records complete
36000 records complete
37000 records complete
38000 records complete
39000 records complete
40000 records complete
41000 records complete
42000 records complete
43000 records complete
44000 records complete
45000 records complete
46000 records complete
47000 records complete
48000 records complete
49000 records complete
50000 records complete
51000 records complete
52000 records complete
53000 records complete
54000 records complete
55000 records complete
56000 records complete
57000 records complete
58000 records complete
59000 records complete
60000 records complete
61000 records complete
62000 records complete
63000 records complete
64000 records complete
65000 records complete
66000 records complete
67000 records complete
68000 records complete
69000 records complete
70000 records complete
71000 records complete
72000 records complete
73000 records complete
74000 records complete
75000 records complete
76000 records complete
77000 records complete
78000 records complete
79000 records complete
80000 records complete
81000 records complete
82000 records complete
83000 records complete
84000 records complete
85000 records complete
86000 records complete
87000 records complete
88000 records complete
89000 records complete
90000 records complete
91000 records complete
92000 records complete
93000 records complete
94000 records complete
95000 records complete
96000 records complete
97000 records complete
98000 records complete
99000 records complete
100000 records complete
101000 records complete
102000 records complete
103000 records complete
104000 records complete
105000 records complete
106000 records complete
107000 records complete
108000 records complete
109000 records complete
110000 records complete
111000 records complete
112000 records complete
113000 records complete
114000 records complete
115000 records complete
116000 records complete
117000 records complete
118000 records complete
119000 records complete
120000 records complete
121000 records complete
122000 records complete
123000 records complete
124000 records complete
125000 records complete
126000 records complete
127000 records complete
128000 records complete
129000 records complete
130000 records complete
131000 records complete
132000 records complete
133000 records complete
134000 records complete
135000 records complete
136000 records complete
137000 records complete
138000 records complete
139000 records complete
140000 records complete
141000 records complete
142000 records complete
143000 records complete
144000 records complete
145000 records complete
146000 records complete
147000 records complete
148000 records complete
149000 records complete
150000 records complete
151000 records complete
152000 records complete
153000 records complete
154000 records complete
155000 records complete
156000 records complete
157000 records complete
158000 records complete
159000 records complete
160000 records complete
161000 records complete
162000 records complete
163000 records complete
164000 records complete
165000 records complete
166000 records complete
167000 records complete
168000 records complete
169000 records complete
170000 records complete
171000 records complete
172000 records complete
173000 records complete
174000 records complete
175000 records complete
176000 records complete
177000 records complete
178000 records complete
179000 records complete
180000 records complete
181000 records complete
182000 records complete
183000 records complete
184000 records complete
185000 records complete
186000 records complete
187000 records complete
188000 records complete
189000 records complete
190000 records complete
191000 records complete
192000 records complete
193000 records complete
194000 records complete
195000 records complete
196000 records complete
197000 records complete
198000 records complete
199000 records complete
200000 records complete
201000 records complete
202000 records complete
203000 records complete
204000 records complete
205000 records complete
206000 records complete
207000 records complete
208000 records complete
209000 records complete
210000 records complete
211000 records complete
212000 records complete
213000 records complete
214000 records complete
215000 records complete
216000 records complete
217000 records complete
218000 records complete
219000 records complete
220000 records complete
221000 records complete
222000 records complete
223000 records complete
224000 records complete
225000 records complete
226000 records complete
227000 records complete
228000 records complete
229000 records complete
230000 records complete
231000 records complete
232000 records complete
233000 records complete
234000 records complete
235000 records complete
236000 records complete
237000 records complete
238000 records complete
239000 records complete
240000 records complete
241000 records complete
242000 records complete
243000 records complete
244000 records complete
245000 records complete
246000 records complete
247000 records complete
248000 records complete
249000 records complete
250000 records complete
251000 records complete
252000 records complete
253000 records complete
254000 records complete
255000 records complete
256000 records complete
257000 records complete
258000 records complete
259000 records complete
260000 records complete
261000 records complete
262000 records complete
263000 records complete
264000 records complete
265000 records complete
266000 records complete
267000 records complete
268000 records complete
269000 records complete
270000 records complete
271000 records complete
272000 records complete
273000 records complete
274000 records complete
275000 records complete
276000 records complete
277000 records complete
278000 records complete
279000 records complete
280000 records complete
281000 records complete
282000 records complete
283000 records complete
284000 records complete
285000 records complete
286000 records complete
287000 records complete
288000 records complete
289000 records complete
290000 records complete
291000 records complete
292000 records complete
293000 records complete
294000 records complete
295000 records complete
296000 records complete
297000 records complete
298000 records complete
299000 records complete
300000 records complete
301000 records complete
302000 records complete
303000 records complete
304000 records complete
305000 records complete
306000 records complete
307000 records complete
308000 records complete
309000 records complete
310000 records complete
311000 records complete
312000 records complete
313000 records complete
314000 records complete
315000 records complete
316000 records complete
317000 records complete
318000 records complete
319000 records complete
320000 records complete
321000 records complete
322000 records complete
323000 records complete
324000 records complete
325000 records complete
326000 records complete
327000 records complete
328000 records complete
329000 records complete
330000 records complete
331000 records complete
332000 records complete
333000 records complete
334000 records complete
335000 records complete
336000 records complete
337000 records complete
338000 records complete
339000 records complete
340000 records complete
341000 records complete
342000 records complete
343000 records complete
344000 records complete
345000 records complete
346000 records complete
347000 records complete
348000 records complete
349000 records complete
350000 records complete
351000 records complete
352000 records complete
353000 records complete
354000 records complete
355000 records complete
356000 records complete
357000 records complete
358000 records complete
359000 records complete
360000 records complete
361000 records complete
362000 records complete
363000 records complete
364000 records complete
365000 records complete
366000 records complete
367000 records complete
368000 records complete
369000 records complete
370000 records complete
371000 records complete
372000 records complete
373000 records complete
374000 records complete
375000 records complete
376000 records complete
377000 records complete
378000 records complete
379000 records complete
380000 records complete
381000 records complete
382000 records complete
383000 records complete
384000 records complete
385000 records complete
386000 records complete
387000 records complete
388000 records complete
389000 records complete
390000 records complete
391000 records complete
392000 records complete
393000 records complete
394000 records complete
395000 records complete
396000 records complete
397000 records complete
398000 records complete
399000 records complete
400000 records complete
401000 records complete
402000 records complete
403000 records complete
404000 records complete
405000 records complete
406000 records complete
407000 records complete
408000 records complete
409000 records complete
410000 records complete
411000 records complete
412000 records complete
413000 records complete
414000 records complete
415000 records complete
416000 records complete
417000 records complete
418000 records complete
419000 records complete
420000 records complete
421000 records complete
422000 records complete
423000 records complete
424000 records complete
425000 records complete
426000 records complete
427000 records complete
428000 records complete
429000 records complete
430000 records complete
431000 records complete
432000 records complete
433000 records complete
434000 records complete
435000 records complete
436000 records complete
437000 records complete
438000 records complete
439000 records complete
440000 records complete
441000 records complete
442000 records complete
443000 records complete
444000 records complete
445000 records complete
446000 records complete
447000 records complete
448000 records complete
449000 records complete
450000 records complete
451000 records complete
452000 records complete
453000 records complete
454000 records complete
455000 records complete
456000 records complete
457000 records complete
458000 records complete
459000 records complete
460000 records complete
461000 records complete
462000 records complete
463000 records complete
464000 records complete
465000 records complete
466000 records complete
467000 records complete
468000 records complete
469000 records complete
470000 records complete
471000 records complete
472000 records complete
473000 records complete
474000 records complete
475000 records complete
476000 records complete
477000 records complete
478000 records complete
479000 records complete
480000 records complete
481000 records complete
482000 records complete
483000 records complete
484000 records complete
485000 records complete
486000 records complete
487000 records complete
488000 records complete
489000 records complete
490000 records complete
491000 records complete
492000 records complete
493000 records complete
494000 records complete
495000 records complete
496000 records complete
497000 records complete
498000 records complete
499000 records complete
500000 records complete
501000 records complete
502000 records complete
503000 records complete
504000 records complete
505000 records complete
506000 records complete
507000 records complete
508000 records complete
509000 records complete
510000 records complete
511000 records complete
512000 records complete
513000 records complete
514000 records complete
515000 records complete
516000 records complete
517000 records complete
518000 records complete
519000 records complete
520000 records complete
521000 records complete
522000 records complete
523000 records complete
524000 records complete
525000 records complete
526000 records complete
527000 records complete
528000 records complete
529000 records complete
530000 records complete
531000 records complete
532000 records complete
533000 records complete
534000 records complete
535000 records complete
536000 records complete
537000 records complete
538000 records complete
539000 records complete
540000 records complete
541000 records complete
542000 records complete
543000 records complete
544000 records complete
545000 records complete
546000 records complete
547000 records complete
548000 records complete
549000 records complete
550000 records complete
551000 records complete
552000 records complete
553000 records complete
554000 records complete
555000 records complete
556000 records complete
557000 records complete
558000 records complete
559000 records complete
560000 records complete
561000 records complete
562000 records complete
563000 records complete
564000 records complete
565000 records complete
566000 records complete
567000 records complete
568000 records complete
569000 records complete
570000 records complete
571000 records complete
572000 records complete
573000 records complete
574000 records complete
575000 records complete
576000 records complete
577000 records complete
578000 records complete
579000 records complete
580000 records complete
581000 records complete
582000 records complete
583000 records complete
584000 records complete
585000 records complete
586000 records complete
587000 records complete
588000 records complete
589000 records complete
590000 records complete
591000 records complete
592000 records complete
593000 records complete
594000 records complete
595000 records complete
596000 records complete
597000 records complete
598000 records complete
599000 records complete
600000 records complete
601000 records complete
602000 records complete
603000 records complete
604000 records complete
605000 records complete
606000 records complete
607000 records complete
608000 records complete
609000 records complete
610000 records complete
611000 records complete
612000 records complete
613000 records complete
614000 records complete
615000 records complete
616000 records complete
617000 records complete
618000 records complete
619000 records complete
620000 records complete
621000 records complete
622000 records complete
623000 records complete
624000 records complete
625000 records complete
626000 records complete
627000 records complete
628000 records complete
629000 records complete
630000 records complete
631000 records complete
632000 records complete
633000 records complete
634000 records complete
635000 records complete
636000 records complete
637000 records complete
638000 records complete
639000 records complete
640000 records complete
641000 records complete
642000 records complete
643000 records complete
644000 records complete
645000 records complete
646000 records complete
647000 records complete
648000 records complete
649000 records complete
650000 records complete
651000 records complete
652000 records complete
653000 records complete
654000 records complete
655000 records complete
656000 records complete
657000 records complete
658000 records complete
659000 records complete
660000 records complete
661000 records complete
662000 records complete
663000 records complete
664000 records complete
665000 records complete
666000 records complete
667000 records complete
668000 records complete
669000 records complete
670000 records complete
671000 records complete
672000 records complete
673000 records complete
674000 records complete
675000 records complete
676000 records complete
677000 records complete
678000 records complete
679000 records complete
680000 records complete
681000 records complete
682000 records complete
683000 records complete
684000 records complete
685000 records complete
686000 records complete
687000 records complete
688000 records complete
689000 records complete
690000 records complete
691000 records complete
692000 records complete
693000 records complete
694000 records complete
695000 records complete
696000 records complete
697000 records complete
698000 records complete

In [6]:
# SAVE PAIR DATA IN CSV FORMAT - userId, productId_pos, userId, productId_neg
all_pairs_np = np.array(all_pairs)

In [ ]:
np.savetxt("data/movielens/train_pair.csv", all_pairs_np, delimiter=",")

In [19]:
# Validation pair
all_users = set(val_data['userId'].unique())
all_items = set(val_data['productId'].unique())

In [20]:
users_negative_samples = {}
for i,u in enumerate(all_users):
    user_u_positive_items = set(val_data[val_data['userId']==u]['productId'].unique())
    user_u_negative_items = all_items.difference(user_u_positive_items)
    users_negative_samples[u] = user_u_negative_items

In [14]:
all_pairs = []
for i ,(userId, productId_pos, _, _) in enumerate(val_data.values):
    sample_negative_items = random.sample(list(users_negative_samples[userId]), 20)
    pair_data_u = [[userId, productId_pos, userId, productId_neg] for productId_neg in sample_negative_items]
    all_pairs.extend(pair_data_u)
    if (i+1) % 1000 == 0:
        print(f"{i+1} records complete")

1000 records complete
2000 records complete
3000 records complete
4000 records complete
5000 records complete
6000 records complete
7000 records complete
8000 records complete
9000 records complete
10000 records complete
11000 records complete
12000 records complete
13000 records complete
14000 records complete
15000 records complete
16000 records complete
17000 records complete
18000 records complete
19000 records complete
20000 records complete
21000 records complete
22000 records complete
23000 records complete
24000 records complete
25000 records complete
26000 records complete
27000 records complete
28000 records complete
29000 records complete
30000 records complete
31000 records complete
32000 records complete
33000 records complete
34000 records complete
35000 records complete
36000 records complete
37000 records complete
38000 records complete
39000 records complete
40000 records complete
41000 records complete
42000 records complete
43000 records complete
44000 records complete
45000 records complete
46000 records complete
47000 records complete
48000 records complete
49000 records complete
50000 records complete
51000 records complete
52000 records complete
53000 records complete
54000 records complete
55000 records complete
56000 records complete
57000 records complete
58000 records complete
59000 records complete
60000 records complete
61000 records complete
62000 records complete
63000 records complete
64000 records complete
65000 records complete
66000 records complete
67000 records complete
68000 records complete
69000 records complete
70000 records complete
71000 records complete
72000 records complete
73000 records complete
74000 records complete
75000 records complete
76000 records complete
77000 records complete
78000 records complete
79000 records complete
80000 records complete
81000 records complete
82000 records complete
83000 records complete
84000 records complete
85000 records complete
86000 records complete
87000 records complete
88000 records complete
89000 records complete
90000 records complete
91000 records complete
92000 records complete
93000 records complete
94000 records complete
95000 records complete
96000 records complete
97000 records complete
98000 records complete
99000 records complete
100000 records complete
101000 records complete
102000 records complete
103000 records complete
104000 records complete
105000 records complete
106000 records complete
107000 records complete
108000 records complete
109000 records complete
110000 records complete
111000 records complete
112000 records complete
113000 records complete
114000 records complete
115000 records complete
116000 records complete
117000 records complete
118000 records complete
119000 records complete
120000 records complete
121000 records complete
122000 records complete
123000 records complete
124000 records complete
125000 records complete
126000 records complete
127000 records complete
128000 records complete
129000 records complete
130000 records complete
131000 records complete
132000 records complete
133000 records complete
134000 records complete
135000 records complete
136000 records complete
137000 records complete
138000 records complete
139000 records complete
140000 records complete
141000 records complete

In [26]:
all_pairs_np = np.array(all_pairs)

In [27]:
np.savetxt("data/movielens/val_pair.csv", all_pairs_np, delimiter=",")

## TRAINER - TRAIN FOR 10 EPOCHS

In [3]:
trainer = GNNTrainer(train_data, movie_features, train_pair_data, val_pair_data)

/home/arnabroy/Workspace/recommendation_system/GNN/architecture.py:187: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_movie_features.sort_index(inplace=True)

In [5]:
trainer.train_data

HeteroData(
  user={ x=[7964] },
  product={ x=[9725] },
  product_feature={ x=[9725, 20] },
  (user, rates, product)={ edge_index=[2, 698113] },
  (product, rated_by, user)={ edge_index=[2, 698113] }
)

In [ ]:
trainer.train(epochs=10, lr=0.0005, decay=10**(-4))

## MEASURE PERFORMANCE - OFFLINE NDCG 24.9%

In [38]:
val_df = pd.read_csv("data/movielens/test.csv", index_col=0)
val_df.head(3)

          userId  productId  rating            timestamp
20011489  195660        541     4.5  2022-10-17 16:31:56
20011492  195660        750     5.0  2022-10-17 16:32:12
20011523  195660       3504     5.0  2022-10-17 16:32:25

In [39]:
with open("models/GNN/model_2.pt", "rb") as f:
    model = torch.load(f)
    f.close()
with open("models/GNN/encoder.pkl", "rb") as f:
    enc = pickle.load(f)
    f.close()
model.to('cpu')
model.final_user_emb = model.final_user_emb.to('cpu')
model.final_item_emb = model.final_item_emb.to('cpu')

/tmp/ipykernel_2038709/4174936051.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(f)

In [40]:
val_df['userId'] = val_df['userId'].map(lambda x: enc.user_id[x])
val_df['productId'] = val_df['productId'].map(lambda x: enc.item_id[x])
val_df.head(5)

          userId  productId  rating            timestamp
20011489    7959         44     4.5  2022-10-17 16:31:56
20011492    7959        867     5.0  2022-10-17 16:32:12
20011523    7959       2869     5.0  2022-10-17 16:32:25
27951262    7962       1386     4.0  2022-10-17 16:32:39
27951145    7962       1695     4.0  2022-10-17 16:32:44

In [41]:
gt_df = val_df.pivot(index='userId', columns='productId', values='rating').fillna(0.0)

In [ ]:
all_users = gt_df.index.values
all_items = gt_df.columns.values

In [42]:
pred = torch.full(size=(gt_df.shape[0], gt_df.shape[1]),fill_value=0.0)

In [43]:
users_xx, items_yy = torch.meshgrid(torch.tensor(all_users) , torch.tensor(all_items))

In [44]:
for i in range(pred.shape[0]):
    users = users_xx[i]
    items = items_yy[i]
    ratings = model.predict(users, items)
    pred[i] = ratings

In [45]:
avg_ndcg = ndcg_score(gt_df.values, pred.detach().numpy())
avg_ndcg_20 = ndcg_score(gt_df.values, pred.detach().numpy(), k=20)

In [46]:
print(f"Offline NDCG average is {avg_ndcg*100: 0.2f}%")
print(f"Offline NDCG@20 is {avg_ndcg_20*100: 0.2f}%")

Offline NDCG average is  29.21%
Offline NDCG@20 is  2.66%

## EXPLORING REPRESENTATIONS

In [16]:
movies = pd.read_csv('data/movielens/movies.csv')
ratings = pd.read_csv('data/movielens/train.csv', index_col=0)

In [17]:
with open("models/GNN/best.pt", "rb") as f:
    model = torch.load(f)
    f.close()
with open("models/GNN/encoder.pkl", "rb") as f:
    enc = pickle.load(f)
    f.close()
model.to('cpu')
model.final_user_emb = model.final_user_emb.detach().cpu().numpy()
model.final_item_emb = model.final_item_emb.detach().cpu().numpy()

/tmp/ipykernel_2033931/3233660656.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(f)

In [21]:
# MOST SIMILAR MOVIE PAIRS
movie_sim = model.final_item_emb@model.final_item_emb.T
np.fill_diagonal(movie_sim, -1)
max_pos = unravel_index(movie_sim.argmax(), movie_sim.shape)
movie_1, movie_2 = enc.id_item[max_pos[0]], enc.id_item[max_pos[1]]
print("Most similar movie pairs")
movies[movies['movieId'].isin([movie_1, movie_2])]

Most similar movie pairs

      movieId                     title   genres
3858     3961           Ghoulies (1985)   Horror
6289     6409  Bend of the River (1952)  Western

In [27]:
# Similar movie of any random movie
movie = enc.id_item[2000]
print(movies[movies['movieId'].isin([movie])])
movies[movies['movieId'].isin([movie])]
top_10 = movie_sim[2000].argsort()[::-1][:10]
top_10 = [enc.id_item[x] for x in top_10]
print('\nTop 10 similar movies of the above movie based on the viewing pattern')
movies[movies['movieId'].isin(top_10)]

       movieId                                        title  \
61208   202517  Kung Fu Panda: Secrets of the Scroll (2016)

                                           genres
61208  Action|Adventure|Animation|Children|Comedy

Top 10 similar movies of the above movie based on the viewing pattern

,movieId,title,genres
12223,58559,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
12326,59315,Iron Man (2008),Action|Adventure|Sci-Fi
13363,68954,Up (2009),Adventure|Animation|Children|Drama
21951,112852,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi
22593,115617,Big Hero 6 (2014),Action|Animation|Comedy
25115,122904,Deadpool (2016),Action|Adventure|Comedy|Sci-Fi
25119,122912,Avengers: Infinity War - Part I (2018),Action|Adventure|Sci-Fi
25120,122914,Avengers: Infinity War - Part II (2019),Action|Adventure|Sci-Fi
25121,122916,Thor: Ragnarok (2017),Action|Adventure|Sci-Fi
54254,187593,Deadpool 2 (2018),Action|Comedy|Sci-Fi

In [24]:
movie_sim[np.where(movie_sim < 0)].shape

(9725,)

In [26]:
user = enc.id_user[1048]
print(f"Top 10 rated movies by user {user} ")
df = ratings[ratings['userId'] == user].sort_values(by='rating', ascending=False)
df['movie'] = df['productId'].map(lambda x: movies[movies['movieId']==x]['title'].values[0])
df[['userId', 'movie', 'rating']].iloc[:10]

Top 10 rated movies by user 61485

         userId                                              movie  rating
6303770   61485  The Bee Gees: How Can You Mend a Broken Heart ...     4.0
6302397   61485                                     Mad Max (1979)     4.0
6302398   61485               Road Warrior, The (Mad Max 2) (1981)     4.0
6303526   61485                              Trick 'r Treat (2007)     4.0
6303777   61485                     Spider-Man: No Way Home (2021)     4.0
6301861   61485                         Conan the Barbarian (1982)     4.0
6303778   61485                                  The Batman (2022)     4.0
6303779   61485                                      Scream (2022)     4.0
6301803   61485             Dracula (Bram Stoker's Dracula) (1992)     4.0
6302431   61485                                 Pumpkinhead (1988)     4.0

In [ ]:
with open("models/GNN/best.pt", "rb") as f:
    model = torch.load(f)
    f.close()

/tmp/ipykernel_1997534/3712743250.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(f)

In [25]:
movie_sim

array([[-1.      , 34.80675 , 34.83048 , ..., 28.088045, 24.817478,
        22.38975 ],
       [34.80675 , -1.      , 32.72488 , ..., 30.040165, 26.79695 ,
        26.324774],
       [34.83048 , 32.72488 , -1.      , ..., 26.44548 , 23.2055  ,
        23.001467],
       ...,
       [28.088045, 30.040165, 26.44548 , ..., -1.      , 21.542809,
        21.130142],
       [24.817478, 26.79695 , 23.2055  , ..., 21.542809, -1.      ,
        19.894344],
       [22.38975 , 26.324774, 23.001467, ..., 21.130142, 19.894344,
        -1.      ]], dtype=float32)

In [29]:
model.predict(
    torch.tensor([100, 200], device='cuda:1'),
    torch.tensor([200, 300], device='cuda:1') 
)

TypeError: can't convert cuda:1 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [34]:
next(model.parameters()).device

device(type='cpu')